version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/sources:cached
    command: ./manage.py runserver 0.0.0.0:8080
    ports:
      - 8080:8080
    env_file: dev.env
    environment:
      - ENVIRONMENT=dev

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/sources:cached
    command: pytest
    env_file: dev.env
    environment:
      - ENVIRONMENT=test
